language: java
install: true

os: linux
dist: trusty
sudo: required
jdk: oraclejdk12

script:
  - chmod 777 ./gradlew
  - ./gradlew jar
deploy:
  provider: releases
  api_key: ${GH_TOKEN}
  file: "./build/libs/VorPAL_Internship_2021-1.0-SNAPSHOT.jar"
  skip_cleanup: true